//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anket()
        {
            this.AnketGrup = new HashSet<AnketGrup>();
            this.Havuz = new HashSet<Havuz>();
            this.Izledim = new HashSet<Izledim>();
        }
    
        public int AnketId { get; set; }
        public string AnketAdi { get; set; }
        public Nullable<bool> Pasif { get; set; }
        public Nullable<bool> Tanimsiz { get; set; }
        public Nullable<bool> Sinav { get; set; }
        public string Link { get; set; }
        public Nullable<int> Zaman { get; set; }
        public Nullable<bool> Sonuc { get; set; }
        public string EgitimVeren { get; set; }
        public string Imza { get; set; }
        public Nullable<int> DepartmanId { get; set; }
        public Nullable<int> SehirId { get; set; }
        public Nullable<int> SubeId { get; set; }
        public Nullable<int> UnvanId { get; set; }
        public Nullable<int> SertifikaNotu { get; set; }
    
        public virtual Anket Anket1 { get; set; }
        public virtual Anket Anket2 { get; set; }
        public virtual Departman Departman { get; set; }
        public virtual Sehir Sehir { get; set; }
        public virtual Sube Sube { get; set; }
        public virtual Unvan Unvan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnketGrup> AnketGrup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Havuz> Havuz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izledim> Izledim { get; set; }
    }
}
