//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnketGrup
    {
        public int AnketGupId { get; set; }
        public Nullable<int> AnketId { get; set; }
        public Nullable<int> SoruGrupId { get; set; }
    
        public virtual SoruGrup SoruGrup { get; set; }
        public virtual Anket Anket { get; set; }
    }
}
