//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Havuz
    {
        public int HavuzId { get; set; }
        public Nullable<int> AnketId { get; set; }
        public Nullable<int> SoruID { get; set; }
        public Nullable<int> SoruGrupId { get; set; }
        public Nullable<int> CevapId { get; set; }
        public Nullable<int> CevapGrupId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<double> CevapPuan { get; set; }
        public Nullable<double> SoruPuan { get; set; }
        public Nullable<double> SoruGrupPuan { get; set; }
        public Nullable<System.DateTime> KayitTar { get; set; }
        public Nullable<int> Isimsiz { get; set; }
    
        public virtual CevapGrup CevapGrup { get; set; }
        public virtual User User { get; set; }
        public virtual SoruGrup SoruGrup { get; set; }
        public virtual Cevap Cevap { get; set; }
        public virtual Soru Soru { get; set; }
        public virtual Anket Anket { get; set; }
    }
}
