//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izledim
    {
        public int IzleId { get; set; }
        public Nullable<int> UseId { get; set; }
        public Nullable<int> AnketId { get; set; }
        public Nullable<bool> Izledi { get; set; }
        public Nullable<System.DateTime> IzTarih { get; set; }
        public Nullable<System.DateTime> BitisZaman { get; set; }
    
        public virtual Anket Anket { get; set; }
        public virtual User User { get; set; }
    }
}
