//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LisansKyn
    {
        public int LisansId { get; set; }
        public string VnTc1 { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public string SirketAdi { get; set; }
        public Nullable<int> ModulSayi { get; set; }
        public string IpAdress { get; set; }
    }
}
