//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace survey.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnvanterTakipLisansEntities : DbContext
    {
        public EnvanterTakipLisansEntities()
            : base(survey.Infrastructure.LegacyConnectionStrings.EnvanterTakipLisansEntities)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Lisans> Lisans { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
