//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace survey.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SurveyEntities : DbContext
    {
        public SurveyEntities()
            : base(survey.Infrastructure.LegacyConnectionStrings.SurveyEntities)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bolge> Bolge { get; set; }
        public virtual DbSet<Bolum> Bolum { get; set; }
        public virtual DbSet<CevapGrup> CevapGrup { get; set; }
        public virtual DbSet<Cinsiyet> Cinsiyet { get; set; }
        public virtual DbSet<Departman> Departman { get; set; }
        public virtual DbSet<Egitim> Egitim { get; set; }
        public virtual DbSet<LisansKyn> LisansKyn { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<Sehir> Sehir { get; set; }
        public virtual DbSet<smtpayar> smtpayar { get; set; }
        public virtual DbSet<Sube> Sube { get; set; }
        public virtual DbSet<truefalse> truefalse { get; set; }
        public virtual DbSet<Unvan> Unvan { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Yaka> Yaka { get; set; }
        public virtual DbSet<Yonetici> Yonetici { get; set; }
        public virtual DbSet<Havuz> Havuz { get; set; }
        public virtual DbSet<AnketGrup> AnketGrup { get; set; }
        public virtual DbSet<SoruGrup> SoruGrup { get; set; }
        public virtual DbSet<Cevap> Cevap { get; set; }
        public virtual DbSet<Soru> Soru { get; set; }
        public virtual DbSet<Anket> Anket { get; set; }
        public virtual DbSet<Izledim> Izledim { get; set; }
    }
}
