//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int PersonelId { get; set; }
        public string PersonelAdi { get; set; }
        public string Tc { get; set; }
        public Nullable<int> Unvani { get; set; }
        public string Mail { get; set; }
        public string Resim { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public Nullable<bool> Pasif { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<bool> Admin { get; set; }
    
        public virtual Unvan Unvan { get; set; }
    }
}
