//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS8981

namespace survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class smtpayar
    {
        public int MailId { get; set; }
        public string Sunucu { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Gonderen { get; set; }
        public int Portu { get; set; }
        public bool Ssli { get; set; }
    }
}
