//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoruGrup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoruGrup()
        {
            this.AnketGrup = new HashSet<AnketGrup>();
            this.Havuz = new HashSet<Havuz>();
            this.Soru = new HashSet<Soru>();
        }
    
        public int SoruGrupId { get; set; }
        public string SoruGrupAdi { get; set; }
        public Nullable<int> SoruGrupSira { get; set; }
        public Nullable<double> SoruGrupPuan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnketGrup> AnketGrup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Havuz> Havuz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Soru> Soru { get; set; }
    }
}
