//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Soru()
        {
            this.Havuz = new HashSet<Havuz>();
        }
    
        public int SoruId { get; set; }
        public string SoruAdi { get; set; }
        public Nullable<int> SoruSira { get; set; }
        public Nullable<int> SoruGrupId { get; set; }
        public Nullable<int> CevapGrupId { get; set; }
        public Nullable<double> SoruPuan { get; set; }
    
        public virtual CevapGrup CevapGrup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Havuz> Havuz { get; set; }
        public virtual SoruGrup SoruGrup { get; set; }
    }
}
