//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Havuz = new HashSet<Havuz>();
            this.Izledim = new HashSet<Izledim>();
        }
    
        public int UserId { get; set; }
        public string UserAdi { get; set; }
        public string UserTc { get; set; }
        public Nullable<int> UserUnvan { get; set; }
        public Nullable<int> UserCinsiyet { get; set; }
        public Nullable<System.DateTime> UserDogumTar { get; set; }
        public Nullable<int> UserEgitim { get; set; }
        public Nullable<int> UserYoneticisi { get; set; }
        public Nullable<int> UserBolumu { get; set; }
        public Nullable<int> UserSube { get; set; }
        public Nullable<int> UserYaka { get; set; }
        public Nullable<int> UserBolge { get; set; }
        public Nullable<int> UserSehir { get; set; }
        public Nullable<int> UserDepartman { get; set; }
        public string UserMail { get; set; }
        public string UserResim { get; set; }
        public string UserTelefon { get; set; }
        public string UserAdres { get; set; }
        public Nullable<System.DateTime> UserIseGirisTarihi { get; set; }
        public Nullable<bool> Pasif { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    
        public virtual Bolge Bolge { get; set; }
        public virtual Bolum Bolum { get; set; }
        public virtual Cinsiyet Cinsiyet { get; set; }
        public virtual Departman Departman { get; set; }
        public virtual Egitim Egitim { get; set; }
        public virtual Sehir Sehir { get; set; }
        public virtual Sube Sube { get; set; }
        public virtual Unvan Unvan { get; set; }
        public virtual Yaka Yaka { get; set; }
        public virtual Yonetici Yonetici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Havuz> Havuz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izledim> Izledim { get; set; }
    }
}
